generate_image:
  fields:
    config_entry:
      required: true
      selector:
        config_entry:
          integration: openai_api_conversation
    prompt:
      required: true
      selector:
        text:
          multiline: true
    size:
      required: false
      example: "1024x1024"
      default: "1024x1024"
      selector:
        text:
    quality:
      required: false
      example: "standard"
      default: "standard"
      selector:
        select:
          options:
            - "standard"
            - "hd"
    style:
      required: false
      example: "vivid"
      default: "vivid"
      selector:
        select:
          options:
            - "vivid"
            - "natural"
